name: 'CI: Linux'
on:
  workflow_dispatch:
  push:

jobs:
  build:
    name: "Build (GCC ${{ matrix.gcc }}, ${{ matrix.build_type }}, ${{ matrix.link }}, ${{ matrix.profile }})"
    strategy:
      matrix:
        gcc: ["12", "15"]
        build_type: ["Release", "Debug"]
        link: ["shared", "static"]
        profile: ["laptop"]
      fail-fast: false
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup Conan and sccache
      uses: ./.github/workflows/setup-conan
      with:
        cache-key: ${{ matrix.profile }}-${{ matrix.gcc }}-${{ matrix.build_type }}

    - name: Build
      run: >
        conan create . --build=missing -pr profiles/${{ matrix.profile }}
        -s compiler.version=${{ matrix.gcc }}
        -s build_type=${{ matrix.build_type }}
        -c tools.build:skip_test=False
        -o guanaqo/\*:with_openmp=True
        -o guanaqo/\*:with_mkl=False
        -o \&:with_ocp=True
        -o \&:with_benchmarks=True
        -o \&:shared=${{ matrix.link == 'shared' && 'True' || 'False' }}

    - run: conan cache clean
